import { HIPOTESES_LABELS, HIPOTESES_VALUES } from "./FormTypesAndFields";

export const hipoteses_options: { descricao: string, value: string }[] = [
    {
        descricao: HIPOTESES_LABELS.JUSTA_CAUSA_REVERTIDA_EM_JUIZO,
        value: HIPOTESES_VALUES.JUSTA_CAUSA_REVERTIDA_EM_JUIZO
    },


    {
        descricao: HIPOTESES_LABELS.PAGAMENTO_VERBAS_RESCISORIAS_FORA_DO_PRAZO,
        value: HIPOTESES_VALUES.PAGAMENTO_VERBAS_RESCISORIAS_FORA_DO_PRAZO
    },

    {
        descricao: HIPOTESES_LABELS.PAGAMENTO_PARCELADO_VERBAS_RESCISORIAS,
        value: HIPOTESES_VALUES.PAGAMENTO_PARCELADO_VERBAS_RESCISORIAS
    },

    {
        descricao: HIPOTESES_LABELS.NAO_PAGAMENTO_VERBAS_RESCISORIAS,
        value: HIPOTESES_VALUES.NAO_PAGAMENTO_VERBAS_RESCISORIAS
    },

    {
        descricao: HIPOTESES_LABELS.ASSEDIO_MORAL_HORIZONTAL,
        value: HIPOTESES_VALUES.ASSEDIO_MORAL_HORIZONTAL
    },

    {
        descricao: HIPOTESES_LABELS.ASSEDIO_MORAL_VERTICAL,
        value: HIPOTESES_VALUES.ASSEDIO_MORAL_VERTICAL
    },

    {
        descricao: HIPOTESES_LABELS.DISPENSA_DISCRIMINATORIA_DOENCA,
        value: HIPOTESES_VALUES.DISPENSA_DISCRIMINATORIA_DOENCA
    },


    {
        descricao: HIPOTESES_LABELS.SONEGACAO_VERBAS_TRABALHISTAS,
        value: HIPOTESES_VALUES.SONEGACAO_VERBAS_TRABALHISTAS
    },

    {
        descricao: HIPOTESES_LABELS.DISPENSA_ARBITRATIA_ESTABILIDADE_PROVISORIA,
        value: HIPOTESES_VALUES.DISPENSA_ARBITRATIA_ESTABILIDADE_PROVISORIA
    },

    {
        descricao: HIPOTESES_LABELS.ACIDENTE_TRABALHO,
        value: HIPOTESES_VALUES.ACIDENTE_TRABALHO
    },

    {
        descricao: HIPOTESES_LABELS.NAO_FORNECIMENTO_EPI_LABOR_INSALUBRE,
        value: HIPOTESES_VALUES.NAO_FORNECIMENTO_EPI_LABOR_INSALUBRE
    },

    {
        descricao: HIPOTESES_LABELS.NAO_FORNECIMENTO_EPI_LABOR_PERIGOSO,
        value: HIPOTESES_VALUES.NAO_FORNECIMENTO_EPI_LABOR_PERIGOSO
    },

    {
        descricao: HIPOTESES_LABELS.EXCESSO_HORAS_EXTRAS,
        value: HIPOTESES_VALUES.EXCESSO_HORAS_EXTRAS
    },
]