export const PASSOS = {
    step1: { etapa: '1', titulo: 'dados do reclamante' },
    step2: { etapa: '2', titulo: 'dados da(s) reclamada(s)' },
    step3: { etapa: '3', titulo: 'foro competente' },
    step4: { etapa: '4', titulo: 'dados do contrato de trabalho' },
    step5: { etapa: '5', titulo: 'dos pedidos do processo' },
    step6: { etapa: 'vinculo_empregaticio', titulo: 'reconhecimento de vínculo empregatício' },
    step7: { etapa: 'insalubridade', titulo: 'adicional de insalubridade' },
    step8: { etapa: 'periculosidade', titulo: 'adicional de periculosidade' },
    step9: { etapa: 'reversao_justa_causa', titulo: 'reversão de justa causa' },
    step10: { etapa: 'diferencas_salariais', titulo: 'diferenças salariais' },
    step11: { etapa: 'gorjetas', titulo: 'gorjetas' },
    step12: { etapa: 'rescisao_indireta', titulo: 'rescisão indireta do contrato de trabalho' },
    step13: { etapa: 'ferias', titulo: 'férias' },
    step14: { etapa: 'multa_477', titulo: 'Multa Art. 477 CLT' },
    step15: { etapa: 'gratuidade_justica', titulo: 'Justiça Gratuita' },
    step16: { etapa: 'falta_deposito_fgts', titulo: 'Falta de depósito de FGTS' },
    step17: { etapa: 'garantia_provisoria_emprego', titulo: 'Garantia provisória de emprego' },
    step18: { etapa: 'aviso_previo', titulo: 'Aviso Prévio' },
    step19: { etapa: 'jornada_trabalho', titulo: 'Jornada de Trabalho' },
    step20: { etapa: 'danos_morais', titulo: 'Danos Morais' },
    step21: { etapa: 'integracao_parcelas', titulo: 'Integração de parcelas pagas em dinheiro' },
    step22: { etapa: 'configuracoes_finais', titulo: 'Configurações Finais' },
}