import { SITUACAO_FERIAS_RECLAMANTE_LABEL, SITUACAO_FERIAS_RECLAMANTE_VALUE } from "./FormTypesAndFields";

export const opcoes_situacao_ferias_reclamante: { descricao: string, value: string }[] = [

    {
        descricao: SITUACAO_FERIAS_RECLAMANTE_LABEL.FERIAS_INTERROMPIDAS_INJUSTAMENTE,
        value: SITUACAO_FERIAS_RECLAMANTE_VALUE.FERIAS_INTERROMPIDAS_INJUSTAMENTE
    },

    {
        descricao: SITUACAO_FERIAS_RECLAMANTE_LABEL.FERIAS_NAO_GOZADAS,
        value: SITUACAO_FERIAS_RECLAMANTE_VALUE.FERIAS_NAO_GOZADAS
    },

    {
        descricao: SITUACAO_FERIAS_RECLAMANTE_LABEL.PAGAMENTO_INTEMPESTIVO_FERIAS,
        value: SITUACAO_FERIAS_RECLAMANTE_VALUE.PAGAMENTO_INTEMPESTIVO_FERIAS
    },

    {
        descricao: SITUACAO_FERIAS_RECLAMANTE_LABEL.FERIAS_PAGAS_NAO_GOZADAS,
        value: SITUACAO_FERIAS_RECLAMANTE_VALUE.FERIAS_PAGAS_NAO_GOZADAS
    },

    {
        descricao: SITUACAO_FERIAS_RECLAMANTE_LABEL.AUSENCIA_APAGAMENTO_TERCO_CONSTITUICIONAL,
        value: SITUACAO_FERIAS_RECLAMANTE_VALUE.AUSENCIA_APAGAMENTO_TERCO_CONSTITUICIONAL
    },
]