export const estados_brasileiros = [
    { value: 'AC', descricao: 'Acre' },
    { value: 'AL', descricao: 'Alagoas' },
    { value: 'AP', descricao: 'Amapá' },
    { value: 'AM', descricao: 'Amazonas' },
    { value: 'BA', descricao: 'Bahia' },
    { value: 'CE', descricao: 'Ceará' },
    { value: 'DF', descricao: 'Distrito Federal' },
    { value: 'ES', descricao: 'Espírito Santo' },
    { value: 'GO', descricao: 'Goiás' },
    { value: 'MA', descricao: 'Maranhão' },
    { value: 'MT', descricao: 'Mato Grosso' },
    { value: 'MS', descricao: 'Mato Grosso do Sul' },
    { value: 'MG', descricao: 'Minas Gerais' },
    { value: 'PA', descricao: 'Pará' },
    { value: 'PB', descricao: 'Paraíba' },
    { value: 'PR', descricao: 'Paraná' },
    { value: 'PE', descricao: 'Pernambuco' },
    { value: 'PI', descricao: 'Piauí' },
    { value: 'RJ', descricao: 'Rio de Janeiro' },
    { value: 'RN', descricao: 'Rio Grande do Norte' },
    { value: 'RS', descricao: 'Rio Grande do Sul' },
    { value: 'RO', descricao: 'Rondônia' },
    { value: 'RR', descricao: 'Roraima' },
    { value: 'SC', descricao: 'Santa Catarina' },
    { value: 'SP', descricao: 'São Paulo' },
    { value: 'SE', descricao: 'Sergipe' },
    { value: 'TO', descricao: 'Tocantins' }
];
