import { HIPOTESE_LABELS, HIPOTESE_VALUES } from "./FormTypesAndFields";

const hipoteses_options: { descricao: string, value: string }[] = [
    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_NAO_PAGAS,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_NAO_PAGAS
    },

    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_NAO_PAGAS_SEGUNDA_A_SABADO,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_NAO_PAGAS_SEGUNDA_A_SABADO
    },

    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_NAO_PAGAS_SABADOS,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_NAO_PAGAS_SABADOS
    },

    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_NAO_PAGAS_SEGUNDA_A_SEXTA,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_NAO_PAGAS_SEGUNDA_A_SEXTA
    },

    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_PAGAS_PARCIALMENTE,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_PAGAS_PARCIALMENTE
    },

    {
        descricao: HIPOTESE_LABELS.HORAS_EXTRAS_PAGAS_POR_FORA,
        value: HIPOTESE_VALUES.HORAS_EXTRAS_PAGAS_POR_FORA
    },

    {
        descricao: HIPOTESE_LABELS.LABOR_DOMINGOS_SEM_CONTRAPRESTACAO,
        value: HIPOTESE_VALUES.LABOR_DOMINGOS_SEM_CONTRAPRESTACAO
    },

    {
        descricao: HIPOTESE_LABELS.LABOR_EM_FERIADOS,
        value: HIPOTESE_VALUES.LABOR_EM_FERIADOS
    },

    {
        descricao: HIPOTESE_LABELS.JORNADA_TRABALHO_12_36,
        value: HIPOTESE_VALUES.JORNADA_TRABALHO_12_36
    },

    {
        descricao: HIPOTESE_LABELS.SUPRESSAO_INTERVALO_INTRAJORNADA,
        value: HIPOTESE_VALUES.SUPRESSAO_INTERVALO_INTRAJORNADA
    },

    {
        descricao: HIPOTESE_LABELS.SUPRESSAO_INTERVALO_INTERJORNADA,
        value: HIPOTESE_VALUES.SUPRESSAO_INTERVALO_INTERJORNADA
    },

    {
        descricao: HIPOTESE_LABELS.ADICIONAL_NOTURNO,
        value: HIPOTESE_VALUES.ADICIONAL_NOTURNO
    },

    {
        descricao: HIPOTESE_LABELS.SOBREAVISO,
        value: HIPOTESE_VALUES.SOBREAVISO
    },

    {
        descricao: HIPOTESE_LABELS.PRONTIDAO,
        value: HIPOTESE_VALUES.PRONTIDAO
    },

    {
        descricao: HIPOTESE_LABELS.DESCARACTERIZACAO_CARGO_CONFIANCA,
        value: HIPOTESE_VALUES.DESCARACTERIZACAO_CARGO_CONFIANCA
    },



]