import { OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_LABEL, OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_VALUE } from "./FormTypesAndFields";

export const opcoes_pagamento_verbas_rescisorias: { descricao: string, value: string }[] = [
    {
        descricao: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_LABEL.NAO_PAGAS_DENTRO_PRAZO,
        value: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_VALUE.NAO_PAGAS_DENTRO_PRAZO
    },

    {
        descricao: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_LABEL.PAGAS_FORA_DO_PRAZO_LEGAL,
        value: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_VALUE.PAGAS_FORA_DO_PRAZO_LEGAL
    },

    {
        descricao: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_LABEL.PAGAS_FORMA_PARCELADA,
        value: OPCAO_PAGAMENTO_VERBAS_RESCISORIAS_VALUE.PAGAS_FORMA_PARCELADA
    }
]