import { Checkbox } from "@/app/types/checkbox";
import { PEDIDOS_CHAVES_IGUAIS_A_API } from "../../step5/helper/blocos_pedidos_existentes";
import { DemaisCamposActions, DemaisCamposError } from "./DemaisCampos/types";

export interface ErrorStep6 {
    demais_campos: DemaisCamposError
}

export type periodo_vinculo = null | 'todo_periodo' | 'parte_contrato'

export enum RECONHECIMENTO_VINCULO_EMPREGATICIO {
    PERIODO_VINCULO = "periodo_vinculo",
    DATA_INICIO = "data_inicio",
    DATA_FIM = "data_fim",
    PJ = "pj",
    REPRESENTANTE_COMERCIAL = "representante_comercial",
    EMPREGADO_CLT = "empregado_clt",
    CONTRATO_REPRESENTACAO_COMERCIAL = "contrato_representacao_comercial",
    INSCRICAO_CORE = "inscricao_core",
    REPRESENTACAO_COMERCIAL_MEI = "representacao_comercial_mei",
    MOTORISTA_CARGAS = "motorista_cargas",
    MOTORISTA_VEICULO_PROPRIO = "motorista_veiculo_proprio",
    MOTORISTA_INSCRICAO_ANTT = "motorista_inscricao_antt",
    MOTORISTA_TRES_ANOS_EXPERIENCIA = "motorista_tres_anos_experiencia",
    MOTORISTA_APLICATIVO = "motorista_aplicativo",
    VALOR_ESTIMADO_PEDIDO = "valor_estimado_pedido"
}

export type reconhecimento_vinculo_empregaticio = {
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.PERIODO_VINCULO]: periodo_vinculo,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.DATA_INICIO]: string
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.DATA_FIM]: string
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.PJ]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.REPRESENTANTE_COMERCIAL]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.CONTRATO_REPRESENTACAO_COMERCIAL]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.INSCRICAO_CORE]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.REPRESENTACAO_COMERCIAL_MEI]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_CARGAS]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_VEICULO_PROPRIO]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_INSCRICAO_ANTT]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_TRES_ANOS_EXPERIENCIA]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_APLICATIVO]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.EMPREGADO_CLT]: null | boolean
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.VALOR_ESTIMADO_PEDIDO]: null | number
}

export const reconhecimento_vinculo_empregaticio_initial_value: reconhecimento_vinculo_empregaticio = {
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.PERIODO_VINCULO]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.DATA_INICIO]: "",
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.DATA_FIM]: "",
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.PJ]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.REPRESENTANTE_COMERCIAL]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.CONTRATO_REPRESENTACAO_COMERCIAL]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.INSCRICAO_CORE]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.REPRESENTACAO_COMERCIAL_MEI]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_CARGAS]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_VEICULO_PROPRIO]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_INSCRICAO_ANTT]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_TRES_ANOS_EXPERIENCIA]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.MOTORISTA_APLICATIVO]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.EMPREGADO_CLT]: null,
    [RECONHECIMENTO_VINCULO_EMPREGATICIO.VALOR_ESTIMADO_PEDIDO]: null
}

export enum FormField {
    RECONHECIMENTO_VINCULO_EMPREGATICIO = PEDIDOS_CHAVES_IGUAIS_A_API.RECONHECIMENTO_VINCULO_EMPREGO
}

export type FormState = {
    [FormField.RECONHECIMENTO_VINCULO_EMPREGATICIO]: { value: reconhecimento_vinculo_empregaticio, changed: boolean }
}

export type Action =
    | DemaisCamposActions