export enum BLOCOS_PEDIDOS_EXISTENTES {
    RECONHECIMENTO_VINCULO_EMPREGO = "reconhecimento_vinculo_empregaticio",
    REVERSAO_JUSTA_CAUSA = "reversao_justa_causa",
    DIFERENCAS_SALARIAIS = "diferencas_salariais",
    INTEGRACAO_SALARIAL_PARCELAS_PAGAS_DINHEIRO = "integracao_parcelas",
    GORJETAS = "gorjetas",
    JORNADA_TRABALHO = "jornada_trabalho",
    ADICIONAL_INSALUBRIDADE = "adicional_insalubridade",
    ADICIONAL_PERICULOSIDADE = "adicional_periculosidade",
    FALTA_DEPOSITO_FGTS = "falta_deposito_fgts",
    FERIAS = "ferias",
    RESCISAO_INDIRETA = "rescisao_indireta",
    GARANTIA_PROVISORIA = "garantia_provisoria",
    AVISO_PREVIO = "aviso_previo",
    DANOS_MORAIS = "danos_morais",
    MULTA_ART_467 = "multa_art_467",
    MULTA_ART_477 = "multa_art_477",
    GRATUIDADE_JUSTICA = "gratuidade_justica",
}

export enum PEDIDOS_CHAVES_IGUAIS_A_API {
    ADICIONAL_INSALUBRIDADE = "pedido_adicional_insalubridade",
    ADICIONAL_PERICULOSIDADE = "pedido_adicional_periculosidade",
    AVISO_PREVIO = "pedido_aviso_previo",
    DANOS_MORAIS = "pedido_danos_morais",
    DIFERENCAS_SALARIAIS = "pedido_diferencas_salariais",
    FALTA_DEPOSITO_FGTS = "pedido_falta_deposito_fgts",
    FERIAS = "pedido_ferias",
    GARANTIA_PROVISORIA = "pedido_garantia_provisoria_emprego",
    GORJETAS = "pedido_gorjetas",
    GRATUIDADE_JUSTICA = "pedido_gratuidade_justica",
    JORNADA_TRABALHO = "pedido_jornada_trabalho",
    MULTA_ART_477 = "pedido_multa_477",
    RESCISAO_INDIRETA = "pedido_rescisao_indireta",
    REVERSAO_JUSTA_CAUSA = "pedido_reversao_justa_causa",
    RECONHECIMENTO_VINCULO_EMPREGO = "reconhecimento_vinculo_empregaticio",
    DIFERENCAS_SALARIAIS_ACT_CCT = "pedido_act_cct",
    DIFERENCAS_SALARIAIS_ACUMULO_FUNCAO = "pedido_acumulo_funcao",
    DIFERENCAS_SALARIAIS_SALARIO_SUBSTITUICAO = "pedido_salario_substituicao",
    DIFERENCAS_SALARIAIS_DESVIO_FUNCAO = "pedido_desvio_funcao",
    INTEGRACAO_SALARIAL_PARCELAS_PAGAS_DINHEIRO = "pedido_integracao_parcelas_pagas_dinheiro",
}