import Container from "@/presentation/components/Template/Container"

export const metadata = {
  title: 'Ruke - Inteligência Jurídica',
  description: 'Generated by Next.js',
  icons: '/ruke-favicon.png'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  )
}
