import { NATUREZA_DIVIDA } from "./DividasFormTypesAndFields";

export const natureza_options: { descricao: string, value: string }[] = [
    { descricao: NATUREZA_DIVIDA.EMPRESTIMO_PESSOAL, value: NATUREZA_DIVIDA.EMPRESTIMO_PESSOAL },
    { descricao: NATUREZA_DIVIDA.EMPRESTIMO_CONSIGNADO, value: NATUREZA_DIVIDA.EMPRESTIMO_CONSIGNADO },
    { descricao: NATUREZA_DIVIDA.SERVICOS_ESSENCIAIS, value: NATUREZA_DIVIDA.SERVICOS_ESSENCIAIS },
    { descricao: NATUREZA_DIVIDA.ENERGIA_ELETRICA, value: NATUREZA_DIVIDA.ENERGIA_ELETRICA },
    { descricao: NATUREZA_DIVIDA.AGUA, value: NATUREZA_DIVIDA.AGUA },
    { descricao: NATUREZA_DIVIDA.PLANO_DE_SAUDE, value: NATUREZA_DIVIDA.PLANO_DE_SAUDE },
    { descricao: NATUREZA_DIVIDA.MEDICAMENTOS_ESSENCIAIS, value: NATUREZA_DIVIDA.MEDICAMENTOS_ESSENCIAIS },
    { descricao: NATUREZA_DIVIDA.FATURA_DO_CARTAO_DE_CREDITO, value: NATUREZA_DIVIDA.FATURA_DO_CARTAO_DE_CREDITO },
]